import { useState, type FormEvent } from 'react'
import { clinic, doctors, phone, whatsapp, locations, diagnostics, advancedCare, servicesNote } from './data'
import './App.css'

function Eye({ large = false }: { large?: boolean }) {
  return <svg className={large ? 'eye-art' : 'eye-logo'} viewBox="0 0 400 260" fill="none" aria-hidden="true"><path d="M25 130C75 42 137 26 200 26s125 16 175 104c-50 88-112 104-175 104S75 218 25 130Z" stroke="currentColor" strokeWidth={large ? 2 : 13} /><circle cx="200" cy="130" r="77" stroke="currentColor" strokeWidth={large ? 2 : 11}/><circle cx="200" cy="130" r="48" fill="currentColor"/><circle cx="217" cy="110" r="12" fill={large ? '#eef5fc' : 'white'}/>{large && <><circle cx="200" cy="130" r="100" stroke="currentColor" strokeOpacity=".15"/><path d="M200 0v45m0 170v45M0 130h65m270 0h65" stroke="currentColor" strokeOpacity=".4"/><circle cx="200" cy="130" r="62" stroke="currentColor" strokeDasharray="1 5"/></>}</svg>
}
const Arrow = () => <span aria-hidden="true">↗</span>

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [bookingLink, setBookingLink] = useState('')
  function submitBooking(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const values = new FormData(event.currentTarget)
    const message = `${whatsapp.message}\nName: ${String(values.get('name')).trim()}\nPhone: ${String(values.get('phone')).trim()}\nPreferred location: ${values.get('location')}\nService: ${values.get('service')}`
    const url = new URL(whatsapp.href)
    url.searchParams.set('text', message)
    setBookingLink(url.toString())
  }
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="topline"><div className="container">Specialist eye care in {clinic.country}<a href={phone.href}>{phone.number} <Arrow /></a></div></div>
    <header className="header"><div className="container navigation">
      <a className="brand" href="#" aria-label={`${clinic.name} home`}><Eye /><span>{clinic.name}<small>CARE FOR YOUR VISION</small></span></a>
      <button className="menu-toggle" aria-expanded={menuOpen} aria-controls="navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? 'Close' : 'Menu'} <span aria-hidden="true">{menuOpen ? '×' : '+'}</span></button>
      <nav id="navigation" className={menuOpen ? 'nav open' : 'nav'} aria-label="Main navigation" onClick={() => setMenuOpen(false)}><a href="#services">Our services</a><a href="#doctors">Our doctors</a><a href="#locations">Find us</a><a className="button small" href="#book">Book an appointment <Arrow /></a></nav>
    </div></header>
    <main id="main">
      <section className="hero container">
        <div className="hero-copy"><p className="eyebrow"><span className="dot"/> A CLEARER VIEW STARTS HERE</p><h1>Your vision.<br/>Our <em>focus.</em></h1><p className="intro">Specialist eye care, closer to home. From detailed eye testing to advanced treatment, find your next step at {clinic.name}.</p><div className="actions"><a className="button" href="#book">Book an appointment <Arrow /></a><a className="text-link" href="#services">Explore our care <span aria-hidden="true">↓</span></a></div><div className="hero-foot"><span>Two locations.</span><span>One focus: your eyes.</span></div></div>
        <div className="hero-visual"><div className="visual-top"><span>THE ART OF SEEING CLEARLY</span><span>01 / EYE CARE</span></div><Eye large/><div className="visual-bottom"><span>Clarity begins<br/>with care.</span><span className="visual-plus" aria-hidden="true">+</span></div></div>
      </section>
      <div className="care-strip container"><span><b>01</b> Specialist consultations</span><span><b>02</b> Diagnostic testing</span><span><b>03</b> Advanced eye care</span></div>
      <section className="section container" id="services"><div className="section-heading"><div><p className="eyebrow">OUR SERVICES</p><h2>Care for the way<br/>you see the world.</h2></div><p>Explore our eye testing, treatments and surgical services. Your consultation is the starting point.</p></div>
        <div className="flagships">{[advancedCare[0], advancedCare[1], advancedCare[2], advancedCare[5]].map((service, i) => <a className="service-card" href="#book" key={service}><div className="card-top"><span className="service-number">0{i + 1}</span><Arrow /></div><h3>{service}</h3><span className="card-caption">Enquire about care</span></a>)}</div>
        <div className="service-lists"><div><div className="list-heading"><h3>Diagnostics & testing</h3><span>{String(diagnostics.length).padStart(2, '0')} SERVICES</span></div><ul>{diagnostics.map(service => <li key={service}><span aria-hidden="true">+</span>{service}</li>)}</ul></div><div><div className="list-heading"><h3>Advanced care & surgery</h3><span>{String(advancedCare.length).padStart(2, '0')} SERVICES</span></div><ul>{advancedCare.map(service => <li key={service}><span aria-hidden="true">+</span>{service}</li>)}</ul></div></div><p className="service-note">{servicesNote}.</p>
      </section>
      <section className="doctors-section" id="doctors"><div className="container section"><div className="section-heading"><div><p className="eyebrow">MEET YOUR DOCTORS</p><h2>A personal approach.<br/>Specialist expertise.</h2></div><p>Get to know the eye specialists and surgeons at {clinic.name}.</p></div><div className="doctors-grid">{doctors.map((doctor, i) => <article className="doctor-card" key={doctor.name}><div className="doctor-mark" aria-hidden="true">{i === 0 ? 'SM' : 'KD'}<span>+</span></div><div><p className="eyebrow">{doctor.isPrincipal ? 'PRINCIPAL SPECIALIST' : 'EYE SPECIALIST'}</p><h3>{doctor.name}</h3><p className="credentials">{doctor.credentials}</p><p>{doctor.role}</p></div></article>)}</div></div></section>
      <section className="section container" id="locations"><div className="section-heading"><div><p className="eyebrow">VISIT THE EYE CLINIC</p><h2>Closer to you.</h2></div><p>Find us in Chaguanas and Tacarigua.<br/>Choose the location that works for you.</p></div><div className="locations-grid">{locations.map((location, i) => <article className="location-card" key={location.name}><div className="location-title"><span className="eyebrow">LOCATION 0{i + 1}</span><span aria-hidden="true">↗</span></div><h3>{location.name}</h3><address>{location.address}{'area' in location && <span>{location.area}</span>}</address><div className="hours"><p className="eyebrow">OPENING HOURS</p><p>{location.hours}</p>{'closed' in location && <p className="muted">{location.closed}</p>}</div><a className="text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${location.address}, ${location.name}, ${clinic.country}`)}`} target="_blank" rel="noreferrer">Get directions <Arrow /></a></article>)}</div></section>
      <section className="booking-section" id="book"><div className="container booking-grid"><div className="booking-copy"><p className="eyebrow">LET’S TAKE THE NEXT STEP</p><h2>Make time<br/>for your vision.</h2><p>Request an appointment at your preferred location. Our team will confirm availability with you on WhatsApp.</p><a className="contact-phone" href={phone.href}>{phone.number} <Arrow /></a><a className="text-link" href={whatsapp.href} target="_blank" rel="noreferrer">Chat with us on WhatsApp <Arrow /></a></div><form className="booking-form" onSubmit={submitBooking} onChange={() => setBookingLink('')}><h3>Request an appointment</h3><p>Start with a few details.</p><label htmlFor="name">Full name</label><input id="name" name="name" autoComplete="name" placeholder="Your full name" required maxLength={100} pattern=".*\S.*"/><label htmlFor="phone">Phone number</label><input id="phone" name="phone" type="tel" autoComplete="tel" placeholder="Your contact number" required maxLength={30} pattern="[+0-9()\s.\-]{7,30}"/><label htmlFor="location">Preferred location</label><select id="location" name="location" required defaultValue=""><option value="" disabled>Select a location</option>{locations.map(location => <option key={location.name}>{location.name}</option>)}</select><label htmlFor="service">What can we help with?</label><select id="service" name="service" defaultValue="General consultation"><option>General consultation</option><optgroup label="Diagnostics & testing">{diagnostics.map(service => <option key={service}>{service}</option>)}</optgroup><optgroup label="Advanced care & surgery">{advancedCare.map(service => <option key={service}>{service}</option>)}</optgroup></select><button className="button" type="submit">Prepare appointment request <Arrow /></button><p className="form-note">Your details will be included in a WhatsApp message for you to review and send. An appointment is confirmed only after our team responds.</p>{bookingLink && <div className="booking-result" role="status"><strong>Your request is ready.</strong><p>Open WhatsApp to review and send it to our team.</p><a className="button" href={bookingLink} target="_blank" rel="noreferrer">Continue to WhatsApp <Arrow /></a></div>}</form></div></section>
    </main>
    <footer className="container footer"><a className="brand" href="#"><Eye/><span>{clinic.name}<small>CARE FOR YOUR VISION</small></span></a><p>{clinic.country}</p><a href={phone.href}>{phone.number}</a><span className="copyright">© {new Date().getFullYear()} {clinic.name}</span></footer>
    <div className="sticky-actions" aria-label="Quick contact"><a href={phone.href}>Call the clinic <span aria-hidden="true">↗</span></a><a href="#book">Book an appointment <Arrow /></a></div>
  </>
}
export default App
